### All User

GET http://localhost:5000/user/list
Content-Type: application/json

### One User

GET http://localhost:5000/user/2b666847-549e-42d4-a61c-f43d2b43e445
Content-Type: application/json

### Create a new User

POST http://localhost:5000/user
Content-Type: application/json

{
  "name": "Italo",
  "email": "italo@gmail.com",
  "password": "password",
  "avatar": "http://google.api/13412343"
}

### Update a User
PATCH http://localhost:5000/user/2b666847-549e-42d4-a61c-f43d2b43e445
Content-Type: application/json

{
  "name": "Italo Brito",
  "email": "italo@gmail.com",
  "password": "password",
  "avatar": "http://google.api/13412343"
}

### Delete a User
DELETE http://localhost:5000/user/2b666847-549e-42d4-a61c-f43d2b43e445
Content-Type: application/json